##For Data Science there are few popular libraries in python
###Processing
1)numpy

2)pandas

3)scipy
###Visualisation
4)matplotlib

5)seaborn
###Machine Learning
6)statsmodels

7)sklearn
###Deep Learning
8)tensorflow

9)keras

10)pytorch



#Numpy

In [ ]:
import numpy as np

In [ ]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]], dtype = int)
print(a)
print(type(a))
print(a.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
<class 'numpy.ndarray'>
(3, 4)


In [ ]:
# a[row,col]
a[0,1:]

array([2, 3, 4])

In [ ]:
b = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],
 [[1,2,3,4],[5,6,7,8],[9,10,11,12]],
 [[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
print(b)
print(b.shape)


[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
(3, 3, 4)


In [ ]:
# range and ocnversion function in numpy
a = np.arange(0,10,2)
print(len(a))
a = a.reshape((5,1))
print(a)
l = a.tolist()
print(l)
s = a.tostring()
print(s)
a.fill(0)
print(a)
c = a.copy()
print(a)

[[0]
 [2]
 [4]
 [6]
 [8]]
[[0], [2], [4], [6], [8]]
b'\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00\x06\x00\x00\x00\x00\x00\x00\x00\x08\x00\x00\x00\x00\x00\x00\x00'
[[0]
 [0]
 [0]
 [0]
 [0]]
[[0]
 [0]
 [0]
 [0]
 [0]]


In [ ]:
# for converting into a 1d array
b.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12,  1,  2,  3,  4,  5,
        6,  7,  8,  9, 10, 11, 12,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10,
       11, 12])

In [ ]:
# for concatinating arrays
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

### axis represents the dimension in which adding should be done
c = np.concatenate((a,b), axis=0)
print(c)
c = np.concatenate((a,b), axis=1)
print(c)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
# we can expand dimension of the array
a = np.array([1,2,3,4])
print(a[np.newaxis,:])
print(a[:,np.newaxis])

[[1 2 3 4]]
[[1]
 [2]
 [3]
 [4]]


In [ ]:
b = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],
              [[1,2,3,4],[5,6,7,8],[9,10,11,12]],
              [[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
print(b[np.newaxis,:])
print('\n\n')
print(b[:,np.newaxis])

[[[[ 1  2  3  4]
   [ 5  6  7  8]
   [ 9 10 11 12]]

  [[ 1  2  3  4]
   [ 5  6  7  8]
   [ 9 10 11 12]]

  [[ 1  2  3  4]
   [ 5  6  7  8]
   [ 9 10 11 12]]]]



[[[[ 1  2  3  4]
   [ 5  6  7  8]
   [ 9 10 11 12]]]


 [[[ 1  2  3  4]
   [ 5  6  7  8]
   [ 9 10 11 12]]]


 [[[ 1  2  3  4]
   [ 5  6  7  8]
   [ 9 10 11 12]]]]


In [ ]:
# we can create an array of zeros or ones
a = np.zeros((2,3))
print(a)
a = np.ones((2,3))
print(a)
b = np.zeros_like(a)
print(b)
b = np.ones_like(a)
print(b)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# for finding a transpose of a matrix
a = np.array([[1,2,3,4]])
print(a)
print(a.transpose())

[[1 2 3 4]]
[[1]
 [2]
 [3]
 [4]]


In [ ]:
# for creating identity matirces
a = np.identity(4,float)
print(a)
print()
# for creating a matrix with ones along the kth diagonal
a = np.eye(4, k=1,dtype=float)
print(a)
print()
a = np.eye(4,M=8, k=1,dtype=float)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]

[[0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]]


In [ ]:
# general mathematical calculations on numpy arrays
a = np.array([1,2,3], dtype=float)
b = np.array([4,5,6], dtype=float)
print(a+b)
print(a-b)
print(a*b)
print(a**b)
print(a/b)
print(a%b)

[5. 7. 9.]
[-3. -3. -3.]
[ 4. 10. 18.]
[  1.  32. 729.]
[0.25 0.4  0.5 ]
[1. 2. 3.]


In [ ]:
# some math function and constants
b = np.array([4.56,5.32,6.62], dtype=float)
print(np.sqrt(b))
print(np.ceil(b))
print(np.floor(b))

# rounding for nearest integer
print(np.rint(b))

[2.13541565 2.30651252 2.57293607]
[5. 6. 7.]
[4. 5. 6.]
[5. 5. 7.]


In [ ]:
print(np.pi)
print(np.e)
print(np.NaN)
print(np.NAN)
print(np.Inf)
print(np.Infinity)

3.141592653589793
2.718281828459045
nan
nan
inf
inf


In [ ]:
# basic matrix operations
a = np.array([1,2,3,4])
print(a.sum())
# we can also use np.sum(a)
print(a.prod())
# we can also use np.prod(a)

10
24


In [ ]:
# we can find avg, varience, standard deviation
a = np.array([2,1,9],float)
print(a.mean())
# we can also use np.mean(a)
print(a.var())
# we can also use np.var(a)
print(a.std())
# we can also use np.std(a)

4.0
12.666666666666666
3.559026084010437


In [ ]:
a = np.array([2,1,9],float)

# we can find min and max of an array and their index values
print(a.min())
# we can also use np.min(a)
print(a.max())
# we can also use np.max(a)
print(a.argmin())
# we can also use np.argmin(a)
print(a.argmax())
# we can also use np.argmax(a)

1.0
9.0
1
2


In [ ]:
# we can also find mean based on axis
a = np.array([[1,2],[3,4],[5,6]], dtype=float)
print(a.mean())
print(a.mean(axis=0))
print(a.mean(axis=1))
print(a.shape)

3.5
[3. 4.]
[1.5 3.5 5.5]
(3, 2)


In [ ]:
# we can also sort the elements
a = np.array([2,1,9],float)

a.sort()
print(a)
# we can also use np.sort(a)

[1. 2. 9.]


In [ ]:
# we can limit the max and min values in an array
a = np.array([2,1,9,-5,10],float)
print(a.clip(0,10))

# we can delete duplicate elements 
a = np.array([2,1,9,9,1,-5,10],float)
print(np.unique(a))

[ 2.  1.  9.  0. 10.]
[-5.  1.  2.  9. 10.]


In [ ]:
# we can find the diagonal elements of a square matrtix
a = np.array([[1,2],[3,4]])
print(np.diagonal(a))

[1 4]


In [ ]:
# we can also perform element wise comparision and logical operators on numpy arrays
a = np.array([1,2,5], dtype=float)
b = np.array([4,1,5], dtype=float)

print(a > b)
print(a == b)
print(a > 2)
print()
# we can find whether any or all the values present in a numpy array are true or not
c = a > 2
print(any(c))
c = a > 2
print(all(c))
print()
# logical operators
print(np.logical_and(a>1,a<10))
print(np.logical_or(a>1,a<5))
print(np.logical_not(a>2))
print(np.logical_xor(a>2,b<5))

[False  True False]
[False False  True]
[False False  True]

True
False

[False  True  True]
[ True  True  True]
[ True  True False]
[ True  True  True]


In [ ]:
# we can generate a numpy array based on condition
a = np.array([1,0,5], dtype=float)
c = np.where(a!=0,a**a,a)
print(c)

[1.000e+00 0.000e+00 3.125e+03]


In [ ]:
# we can select the values of an array based on a condition
a = np.array([1,0,5], dtype=float)

print(a[a>=1])

[1. 5.]


In [ ]:
# values of array can be selected based on other array
a = np.array([1,0,5], dtype=float)
b = np.array([0,0,1,1,0,1],dtype=int)
print(a[b])
# for multi dimensional arrays we have to specify multiple arrays
a = np.array([[1,2],[3,4]],dtype=float)
print(a[b,b])

print()

# similar to above 
a = np.array([1,0,5], dtype=float)
print(a.take(b,axis=0))
a = np.array([[1,2],[3,4]],dtype=float)
print(a.take(b,axis=0))
print(a.take(b, axis=1))

[1. 1. 0. 0. 1. 0.]
[1. 1. 4. 4. 1. 4.]

[1. 1. 0. 0. 1. 0.]
[[1. 2.]
 [1. 2.]
 [3. 4.]
 [3. 4.]
 [1. 2.]
 [3. 4.]]
[[1. 1. 2. 2. 1. 2.]
 [3. 3. 4. 4. 3. 4.]]


In [ ]:
# we can replace values based on other index array
a = np.array([1,0,5], dtype=float)
a.put([0,2],[5,6])
print(a)

In [ ]:
###### Vector and Matrix Mathematics ######
a = np.array([1,2], dtype=int)
b = np.array([[1,2,3],[4,5,6]], dtype=int)
c = np.reshape(a,(2,1))

print(np.dot(a,b))
print(c*b) # here the matrix c will be broadcated to (2,3) and element wise product is computed
'''
c is broadcated as below
[[1,1,1],
 [2,2,2]]
'''

[ 9 12 15]
[[ 1  2  3]
 [ 8 10 12]]


In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.inner(a,b))
print(np.dot(a,b))

print('\n\n')

# for vectors inner and dot product both are same..
a = np.array([[1,2,3],[4,5,6]])
b = np.array([7,8,9])
c = np.array([[10,11,12],[13,14,15]])

print(np.dot(a,b))
print(np.inner(a,b))
print(np.inner(a,c))

32
32



[ 50 122]
[ 50 122]
[[ 68  86]
 [167 212]]


In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.outer(a,b))
print(np.cross(a,b))

[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
[-3  6 -3]


In [ ]:
###### Linear Algebra ######

a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

print(np.linalg.det(a),end='\n\n')
vals,vecs = np.linalg.eig(a)
print(vals)
print(vecs,end='\n\n')
a = np.array([[7,2,8],
              [1,5,9],
              [7,2,10]])
print(np.linalg.inv(a))

0.0

[ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]

[[ 0.48484848 -0.06060606 -0.33333333]
 [ 0.8030303   0.21212121 -0.83333333]
 [-0.5         0.          0.5       ]]


In [ ]:
# we can also load and save numpy arrays into txt files 
a = np.loadtxt('/content/data.txt', dtype=float, skiprows=1)
print(a)

np.savetxt('/content/data1.txt', a, header='value1 value2 value3')

[[0.2536 0.1008 0.3857]
 [0.4839 0.4536 0.3561]
 [0.1292 0.6875 0.5929]
 [0.1781 0.3049 0.8928]
 [0.6253 0.3486 0.8791]]


In [1]:
##### Polynomial Mathematics #####
import numpy as np
# creates the polynomial with given roots
np.poly([-1,1,1,10])

array([  1., -11.,   9.,  11., -10.])

In [2]:
# evaluates the roots
np.roots([1,4,-2,3])

array([-4.5797401 +0.j        ,  0.28987005+0.75566815j,
        0.28987005-0.75566815j])

In [3]:
# evaluates the integration
np.polyint([1,1,1,1])

array([0.25      , 0.33333333, 0.5       , 1.        , 0.        ])

In [4]:
# evaluates the derivative
np.polyder([1/4,1/3,1/2,1,0])

array([1., 1., 1., 1.])

In [6]:
# evealuates a polynomial equation at a particular point of 'x'
np.polyval([1,-2,0,2], 4)

34

In [9]:
# y, the polyfit function can be used to fit a polynomial of specified order to a set of data using a least-squares approach
# return value is a set of polynomial coefficients
x = [1,2,3,4,5,6,7,8]
y = [0,2,1,3,7,10,11,19]
print(np.polyfit(x,y,3))
print(np.polyfit(x,y,2))
print(np.polyfit(x,y,1))

[ 0.03282828 -0.06818182  0.8037518  -0.57142857]
[ 0.375      -0.88690476  1.05357143]
[ 2.48809524 -4.57142857]


In [15]:
##### Statistics #####
a = np.array([1,2,3,4,5,6,7,8,9])
print(a.mean())
print(np.median(a))

b = np.array([[1,2,3,4,5,6,7,8,9],
             [9,8,7,6,5,4,3,2,1]])
# The correlation coefficient for multiple variables observed at multiple instances can be found
#for arrays of the form [[x1, x2, …], [y1, y2, …], [z1, z2, …], …] where x, y, z are different
#observables and the numbers indicate the observation times
print(np.corrcoef(b))

# Here the return array c[i,j] gives the correlation coefficient for the ith and jth observables.
# Similarly, the covariance for data can be found
print(np.cov(b))

5.0
5.0
[[ 1. -1.]
 [-1.  1.]]
[[ 7.5 -7.5]
 [-7.5  7.5]]


In [17]:
##### Random Nubers #####
print(np.random.rand(5))
print(np.random.rand(2,3))
print(np.random.random())
print(np.random.randint(5,10))

#To draw from the discrete Poisson distribution with 𝜆 = 6.0
print(np.random.poisson(6.0))

#To draw from a continuous normal (Gaussian) distribution with mean 𝜇 = 1.5 and standard
#deviation 𝜎 = 4.0:
print(np.random.normal(1.5,4.0))

#To draw from a standard normal distribution (𝜇 = 0, 𝜎 = 1), omit the arguments
print(np.random.normal())

#To draw multiple values, use the optional size argument:
print(np.random.normal(size=5))

# to shuffle a list
a = [1,2,3,4,5,6,7,8,9]
l = np.random.shuffle(a)
print(l)

#to set a random seed 
np.random.seed(21561)

[0.09354112 0.29704459 0.37396762 0.8908598  0.51799047]
[[0.92866181 0.355485   0.75410704]
 [0.14772386 0.81436049 0.03959172]]
0.9186127931511189
9
6
-1.532819260897078
-2.253651446079729
[-0.29116154  0.83842574 -0.39517705 -0.96480859  1.39320845]
None
